project_id = "myfoyoyjtkqthjjvabmn"

[api]
enabled = true
port = 8000
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54321
major_version = 15
